version: '3'

services:
  speedtest:
    container_name: speedtest
    image: rmaz410/sta
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ./data:/var/www/html/data
    ports:
      - 8080:80
      - 8443:443
    environment:
      - CRONJOB_ITERATION=5,20,35,50
